### ISSUE TITLE
[LOCALIZATION] Azure Maya Mystery in Spanish

### ISSUE THREAD

**Issue by cyz** [jlooper/azure-maya-mystery#3]
Hi all, 

There are plans to localize the Azure Maya Mystery for **Spanish** and help more students to learn! 💯 

We need help from the community to review and localize the game.

**[English repo](https://github.com/jlooper/azure-maya-mystery/tree/master/app/game/pyramid)**

Please compare each file below to its original in English and don’t forget to mention in the comments bellow, the file you will be translating/reviewing. Once you review it, please send a PR, if required.

The following files (go to [this folder](https://github.com/jlooper/azure-maya-mystery/tree/master/app/game/pyramid) and review or translate) need to be reviewed:

- [x] README.md
- [x] credits.md
- [ ] habitaciones/1.md
- [x] habitaciones/2.md
- [x] habitaciones/3.md @LucioMSP
- [x] habitaciones/4.md @LucioMSP 
- [x] habitaciones/5.md @LucioMSP 
- [x] habitaciones/6.md
- [ ] habitaciones/7.md
- [ ] habitaciones/8.md
- [x] habitaciones/9.md
- [x] habitaciones/10.md
- [x] habitaciones/11.md
- [ ] habitaciones/12.md
- [x] habitaciones/challenge1.md @LucioMSP

**Comment by cyz** [comment]
@LucioMSP is working to review the all Spanish :)

**Comment by LucioMSP** [comment]
I'm still working on improvements...

**Comment by jlooper** [comment]
hi @LucioMSP - thank you so much for this work! Tania did some edits prior, so please make sure you pull before starting, just in case. Gracias!!

**Comment by LucioMSP** [comment]
Hi @jlooper _ Ok, I'll review before I make any more changes

**Comment by trallard** [comment]
So far all the rooms + extras have been translated. Will mark them as done and just wait for improvements / typo catching from @LucioMSP

**Comment by LucioMSP** [comment]
The 9,10 and the 11.md are OK

**Comment by jlooper** [comment]
hi @LucioMSP  could you also take a look please at the translated strings here:

/app/game/.vuepress/theme/translations

and these:

app/game/.vuepress/theme/utils/items.json

thanks!!

please also add yourself to the credits files!

**Comment by LucioMSP** [comment]
Hi @jlooper sure, not problem.

Here: /app/game/.vuepress/theme/translations - the files "footer.js" and "puzzle.js" OK.

And thanks, I already included myself in the credits.
