### ISSUE TITLE
Unable to register for a new account

### ISSUE THREAD

**Issue by krang312** [jlooper/azure-maya-mystery#31]
It keeps showing that email address is unavailable, even though I've never signed up before (and tried two different email addresses)
<img width="387" alt="AMM issue" src="https://user-images.githubusercontent.com/66268016/83430558-b86c4700-a3ea-11ea-99b8-a3c96a687fa0.PNG">

**Comment by jlooper** [comment]
hi, Kavita, I think you already registered, so you now need to login. I do see your registration in the system. I will add a better message when folks successfully register, directing them to login.
