### ISSUE TITLE
Localization (Nice to have)

### ISSUE THREAD

**Issue by hohanine** [jlooper/azure-maya-mystery#35]
![image](https://user-images.githubusercontent.com/35707656/83581029-86dea300-a4f2-11ea-9270-17400859c44b.png)

Not sure how localized we want to be. Small thing - "Take the picture?" Do we want to have the sentence in Spanish or Portuguese?  

It's a nice to have, not the must I believe.

**Comment by jlooper** [comment]
There are a few missing localizations: 'take a picture' 'my adventure' - will sort those out.

**Comment by jlooper** [comment]
done
