### ISSUE TITLE
Github repo content 

### ISSUE THREAD

**Issue by hohanine** [jlooper/azure-maya-mystery#36]
1. 
![image](https://user-images.githubusercontent.com/35707656/83581153-dc1ab480-a4f2-11ea-8fad-f3083b3d8505.png)
Saw two screenshots in the repo are the same. I wonder if they should be different? 

2. Not yet see the MS Learn modules for Azure App Service Static App recommended in the repo or the game. I recall we want to promote them somehow.

**Comment by jlooper** [comment]
good catch on the screenshots, I've made a few more edits and @softchris can please push those live to the docs when possible. Thanks!
