### ISSUE TITLE
[LOCALIZATION] Azure Maya Mystery in French

### ISSUE THREAD

**Issue by cyz** [jlooper/azure-maya-mystery#4]
Hi all, 

There are plans to localize the Azure Maya Mystery for French and help more students to learn! 💯 

We need help from the community to review and localize the game.

**[English repo](https://github.com/jlooper/azure-maya-mystery/tree/master/app/game/pyramid)**

1)	Create the folder fr under the pyramid ([here](https://github.com/jlooper/azure-maya-mystery/tree/master/app/game/pyramid))
2)	Please compare each file below to its original in English and don’t forget to mention in the comments bellow, the file you will be translating/reviewing. Once you review it, please send a PR, if required.

The following files need to be translated:

- [ ] README.md
- [ ] credits.md
- [ ] habitaciones/1.md
- [ ] habitaciones/2.md
- [ ] habitaciones/3.md
- [ ] habitaciones/4.md
- [ ] habitaciones/5.md
- [ ] habitaciones/6.md
- [ ] habitaciones/7.md
- [ ] habitaciones/8.md
- [ ] habitaciones/9.md
- [ ] habitaciones/10.md
- [ ] habitaciones/11.md
- [ ] habitaciones/12.md
- [ ] habitaciones/challenge1.md

**Comment by ricardoprins** [comment]
I'll start working on it today.

**Comment by cyz** [comment]
thank you @ricardoprins!

**Comment by jlooper** [comment]
hi @ricadoprins could you also take a look please at the translated strings here:

/app/game/.vuepress/theme/translations

and these:

app/game/.vuepress/theme/utils/items.json

thanks!!

please also add yourself to the credits files!

**Comment by jlooper** [comment]
Since the files are now all switched around, it's necessary now to look in the /fr folder for all markdown translations, and in /app/game/.vuepress/theme/translations for js files and the json in app/game/.vuepress/theme/utils/items.json

**Comment by ricardoprins** [comment]
Alright! Pardon me for the delay, I've invited a couple French-speaking friends to help as well

**Comment by jlooper** [comment]
hi! Max did a PR on all the major files; however if you find anything in the items.json or /translations folder please PR! thanks!
