### ISSUE TITLE
Level 3 Spanish translations - please use the dev branch

### ISSUE THREAD

**Issue by jlooper** [jlooper/azure-maya-mystery#70]
game/.vuepress/theme/translations/matching.js
game/.vuepress/theme/translations/challenge3.js
game/.vuepress/theme/translations/puzzle5.js
game/.vuepress/theme/translations/puzzle6.js

all files in

game/pyramid/es/3

and id 14 and to the end of
game/.vuepress/theme/utils/items.json

**Comment by LucioMSP** [comment]
Hi Jen,

Today I was able to review these:

game/.vuepress/theme/translations/matching.js - Done
game/.vuepress/theme/translations/challenge3.js - Done
game/.vuepress/theme/translations/puzzle5.js - Done
game/.vuepress/theme/translations/puzzle6.js

**Comment by jlooper** [comment]
Thank you @LucioMSP !!

**Comment by LucioMSP** [comment]
game/.vuepress/theme/utils/items.json - Done (PR)

**Comment by LucioMSP** [comment]
Finish, send all files to review - @jlooper

**Comment by jlooper** [comment]
Wow thank you!!!

**Comment by jlooper** [comment]
@LucioMSP is there a PR for the final files? thanks again

**Comment by LucioMSP** [comment]
Yeap!, Your welcome!

**Comment by jlooper** [comment]
So sorry, I don't see it, can you give me a link? Maybe I'm missing something @LucioMSP

**Comment by jlooper** [comment]
I found the fork and did the PR... thanks again!! :)
